on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install poetry
      - run: poetry install  
      - run: make test
      - if: ${{ failure() }}
        run: ./inspect_fixtures.sh

  publish:
    # only run on master pushes
    if: github.ref == 'refs/heads/ghcr'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install poetry
      - run: poetry install
      - name: Determine version
        run: echo "VERSION=$(poetry run ./current_version.py)" >>${GITHUB_ENV}
      # Enables builds for different CPU architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into Dockerhub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/reconman/runlike:latest,ghcr.io/reconman/runlike:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
          provenance: false
          push: true